[lint]
select = ["E", "W", "F", "I"]
ignore = ["E501"]
per-file-ignores = { "__init__.py" = ["F401"] }

[format]
indent-style = "space"
line-ending = "lf"
quote-style = "double"

[tool.ruff.lint]
extend-select = [
    "B",   # flake8-bugbear
    "UP",  # pyupgrade
    "I",   # isort
]
target-version = "py311"  # Python versiyonunuza uygun ÅŸekilde
